export const data = [
  {
    col: 0,
    rol: 0,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/1.jpg`),
    intro: `https://medium.com/@vic20087cjimlin/%E7%95%A2%E6%A5%AD%E5%BE%8C%E5%88%B0%E7%95%B6%E5%85%B5%E5%89%8D-%E5%9C%A8%E5%8F%B0%E5%8C%97%E7%9A%84-100-%E5%80%8B%E6%97%A5%E5%AD%90-3271d763bb1d`,
    title: `正職工作`,
  },
  {
    col: 1,
    rol: 0,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/1.gif`),
    intro: `https://ui-animation.firebaseapp.com/1`,
    title: `#1 沖繩`,
    isFull: true
  },
  {
    col: 2,
    rol: 0,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/3.jpeg`),
    intro: `https://medium.com/@vic20087cjimlin/%E7%95%A2%E6%A5%AD%E5%BE%8C%E5%88%B0%E7%95%B6%E5%85%B5%E5%89%8D-%E5%9C%A8%E5%8F%B0%E5%8C%97%E7%9A%84-100-%E5%80%8B%E6%97%A5%E5%AD%90-3271d763bb1d`,
    title: `分享: 街口支付`,
  },
  {
    col: 3,
    rol: 0,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/4.png`),
    intro: `https://qraft.app/`,
    title: `Qraft 匠說`,
  },
  {
    col: 0,
    rol: 1,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/2.gif`),
    intro: ``,
    title: `#2 金曲獎`,
    isFull: true
  },
  {
    col: 1,
    rol: 1,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/6.jpeg`),
    intro: `https://medium.com/@vic20087cjimlin/%E7%95%A2%E6%A5%AD%E5%BE%8C%E5%88%B0%E7%95%B6%E5%85%B5%E5%89%8D-%E5%9C%A8%E5%8F%B0%E5%8C%97%E7%9A%84-100-%E5%80%8B%E6%97%A5%E5%AD%90-3271d763bb1d`,
    title: `分享: Monospace`,
  },
  {
    col: 2,
    rol: 1,
    collen: 1,
    rollen: 1,
    source: ``,
    intro: ``,
    title: `服役`,
  },
  {
    col: 3,
    rol: 1,
    collen: 1,
    rollen: 1,
    source: ``,
    intro: ``,
    title: ``,
    isEmpty: true,
  },
  {
    col: 0,
    rol: 2,
    collen: 1,
    rollen: 1,
    source: ``,
    intro: ``,
    title: ``,
    isEmpty: true,
  },
  {
    col: 1,
    rol: 2,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/10.png`),
    isFull: true,
    intro: `https://107songs.nctu.me/`,
    title: `交大畢業歌投票`,
  },
  {
    col: 2,
    rol: 2,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/11.png`),
    intro: `http://taichi2018.nctu.edu.tw/`,
    title: `<p>TAICHI</p><p>人機互動年會</p>`,
  },
  {
    col: 3,
    rol: 2,
    collen: 1,
    rollen: 1,
    source: ``,
    intro: ``,
    title: `畢業`,
  },
  {
    col: 0,
    rol: 3,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/13.jpg`),
    intro: false,
    title: `<p>H.Spectrum</p><p>鴻海孵化器</p>`,
  },
  {
    col: 1,
    rol: 3,
    collen: 1,
    rollen: 1,
    source: ``,
    intro: false,
    title: `分享: 女人迷`,
  },
  {
    col: 2,
    rol: 3,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/3.gif`),
    intro: `https://ui-animation.firebaseapp.com/3`,
    title: `#3 Gogoro 目錄`,
    isFull: true
  },
  {
    col: 3,
    rol: 3,
    collen: 1,
    rollen: 1,
    source: require(`assets/Design4x4/4.gif`),
    intro: `https://ui-animation.firebaseapp.com/4`,
    title: `#4 白晝之夜`,
    isFull: true
  },
];
